SET SERVEROUTPUT ON;

DECLARE
    V_ALUNO VARCHAR(30) := 'MATHEUS TESTE';
    V_RM NUMBER := 444555666;
BEGIN
    --INSERT INTO ALUNO VALUES(V_RM, V_ALUNO);
    --UPDATE ALUNO
    --SET NOME = V_ALUNO,
    --RA = V_RM
    --WHERE RA = 444555666;
    --COMMIT;
    DELETE FROM ALUNO WHERE RA = 444555666;
    COMMIT
END;


SELECT * FROM ALUNO;

